# Generated by Django 5.2.4 on 2025-07-21 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountings', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviment_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('accounting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moviments', to='accountings.accounting')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moviments', to='banks.bank')),
            ],
        ),
    ]
