# Generated by Django 5.2.4 on 2025-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0002_moviment_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviment',
            options={'ordering': ['-moviment_date']},
        ),
        migrations.AlterField(
            model_name='moviment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moviment',
            name='moviment_date',
            field=models.DateField(),
        ),
    ]
