# Generated by Django 5.2.4 on 2025-07-25 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0003_alter_moviment_options_alter_moviment_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='moviment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
