# Generated by Django 5.2.4 on 2025-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=1)),
            ],
            options={
                'ordering': ['acc_name'],
            },
        ),
    ]
