# Generated by Django 5.2.4 on 2025-07-27 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0001_initial'),
        ('outflows', '0002_alter_outflow_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='accountings.accounting'),
        ),
    ]
