# Generated by Django 5.2.4 on 2025-07-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_alter_outflow_accounting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outflow',
            old_name='payment_methor',
            new_name='payment_method',
        ),
    ]
