# Generated by Django 5.2.4 on 2025-07-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0004_rename_payment_methor_outflow_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='status',
            field=models.CharField(default='NP', max_length=2),
        ),
    ]
